-- MaterialMind V2
-- Central inventory database + transactional import + Windows Auto-Sync Agent
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('admin','operator','viewer');
exception when duplicate_object then null; end $$;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.materials (
  part_no text primary key,
  material_name text,
  material_category text,
  management_code text,
  unit text,
  old_part_no text,
  default_safety_stock numeric not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.inventory_snapshots (
  id uuid primary key default gen_random_uuid(),
  snapshot_date date not null unique,
  source_file_name text not null,
  source_file_hash text not null,
  row_count integer not null default 0,
  imported_by uuid not null references auth.users(id),
  imported_at timestamptz not null default now()
);

create unique index if not exists inventory_snapshots_hash_uq
  on public.inventory_snapshots(source_file_hash);

create table if not exists public.inventory_snapshot_rows (
  snapshot_id uuid not null references public.inventory_snapshots(id) on delete cascade,
  part_no text not null,
  material_name text,
  rating text not null default '',
  warehouse text not null default '',
  storage_bin text not null default '',
  quantity numeric not null default 0,
  safety_stock numeric not null default 0,
  received_date date,
  last_used_date date,
  primary key (snapshot_id, part_no, rating, warehouse, storage_bin)
);

create index if not exists snapshot_rows_lookup_idx
  on public.inventory_snapshot_rows(snapshot_id, part_no, rating, warehouse);

create table if not exists public.inventory_changes (
  id bigint generated by default as identity primary key,
  from_snapshot_id uuid not null references public.inventory_snapshots(id) on delete cascade,
  to_snapshot_id uuid not null references public.inventory_snapshots(id) on delete cascade,
  part_no text not null,
  material_name text,
  rating text not null default '',
  warehouse text not null default '',
  previous_quantity numeric not null default 0,
  current_quantity numeric not null default 0,
  quantity_delta numeric not null default 0,
  change_type text not null check (change_type in ('increase','decrease','new','disappeared')),
  safety_stock numeric not null default 0,
  created_at timestamptz not null default now(),
  unique(to_snapshot_id, part_no, rating, warehouse)
);

create index if not exists inventory_changes_to_idx
  on public.inventory_changes(to_snapshot_id, change_type);

create table if not exists public.import_audit (
  id bigint generated by default as identity primary key,
  snapshot_id uuid references public.inventory_snapshots(id) on delete set null,
  action text not null,
  source_file_name text,
  source_file_hash text,
  row_count integer,
  success boolean not null,
  error_message text,
  operator_id uuid references auth.users(id),
  created_at timestamptz not null default now()
);

create index if not exists import_audit_created_idx on public.import_audit(created_at desc);

-- Windows Agent heartbeat / health status.
create table if not exists public.agent_status (
  machine_name text primary key,
  status text not null default 'WAITING',
  last_file text,
  last_imported_date date,
  last_imported_hash text,
  last_scan_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create index if not exists agent_status_updated_idx on public.agent_status(updated_at desc);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles(user_id, display_name)
  values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', new.email));
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(select 1 from public.profiles where user_id = (select auth.uid()) and role = 'admin');
$$;

create or replace function public.is_operator_or_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists(
    select 1 from public.profiles
    where user_id = (select auth.uid()) and role in ('admin','operator')
  );
$$;

revoke all on function public.is_admin() from public;
revoke all on function public.is_operator_or_admin() from public;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_operator_or_admin() to authenticated;

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch on public.profiles;
create trigger profiles_touch before update on public.profiles for each row execute procedure public.touch_updated_at();
drop trigger if exists materials_touch on public.materials;
create trigger materials_touch before update on public.materials for each row execute procedure public.touch_updated_at();
drop trigger if exists agent_status_touch on public.agent_status;
create trigger agent_status_touch before update on public.agent_status for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.materials enable row level security;
alter table public.inventory_snapshots enable row level security;
alter table public.inventory_snapshot_rows enable row level security;
alter table public.inventory_changes enable row level security;
alter table public.import_audit enable row level security;
alter table public.agent_status enable row level security;

revoke all on table public.profiles, public.materials, public.inventory_snapshots,
  public.inventory_snapshot_rows, public.inventory_changes, public.import_audit, public.agent_status
from anon, authenticated;

grant select on public.profiles, public.materials, public.inventory_snapshots,
  public.inventory_snapshot_rows, public.inventory_changes, public.agent_status to authenticated;
grant update on public.profiles to authenticated;
grant insert, update on public.materials to authenticated;

drop policy if exists profiles_self_select on public.profiles;
create policy profiles_self_select on public.profiles for select to authenticated
using ((select auth.uid()) = user_id or (select public.is_admin()));

drop policy if exists profiles_admin_update on public.profiles;
create policy profiles_admin_update on public.profiles for update to authenticated
using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists materials_read on public.materials;
create policy materials_read on public.materials for select to authenticated using (true);
drop policy if exists materials_admin_insert on public.materials;
create policy materials_admin_insert on public.materials for insert to authenticated with check ((select public.is_admin()));
drop policy if exists materials_admin_update on public.materials;
create policy materials_admin_update on public.materials for update to authenticated using ((select public.is_admin())) with check ((select public.is_admin()));

drop policy if exists snapshots_read on public.inventory_snapshots;
create policy snapshots_read on public.inventory_snapshots for select to authenticated using (true);
drop policy if exists rows_read on public.inventory_snapshot_rows;
create policy rows_read on public.inventory_snapshot_rows for select to authenticated using (true);
drop policy if exists changes_read on public.inventory_changes;
create policy changes_read on public.inventory_changes for select to authenticated using (true);
drop policy if exists audit_admin_read on public.import_audit;
create policy audit_admin_read on public.import_audit for select to authenticated using ((select public.is_admin()));
drop policy if exists agent_status_read on public.agent_status;
create policy agent_status_read on public.agent_status for select to authenticated using (true);

create or replace function public.import_inventory_snapshot(
  p_snapshot_date date,
  p_source_file_name text,
  p_source_file_hash text,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_user uuid := (select auth.uid());
  v_snapshot_id uuid;
  v_previous_id uuid;
  v_row_count integer;
  v_changes integer := 0;
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if not (select public.is_operator_or_admin()) then raise exception 'ROLE_NOT_ALLOWED'; end if;
  if jsonb_typeof(p_rows) <> 'array' then raise exception 'ROWS_MUST_BE_ARRAY'; end if;
  if jsonb_array_length(p_rows) = 0 then raise exception 'ROWS_EMPTY'; end if;
  if length(coalesce(p_source_file_hash,'')) < 32 then raise exception 'INVALID_FILE_HASH'; end if;
  if exists(select 1 from public.inventory_snapshots where snapshot_date = p_snapshot_date) then raise exception 'SNAPSHOT_DATE_ALREADY_EXISTS'; end if;
  if exists(select 1 from public.inventory_snapshots where source_file_hash = p_source_file_hash) then raise exception 'DUPLICATE_FILE'; end if;

  select id into v_previous_id from public.inventory_snapshots
  where snapshot_date < p_snapshot_date order by snapshot_date desc limit 1;

  insert into public.inventory_snapshots(snapshot_date,source_file_name,source_file_hash,row_count,imported_by)
  values(p_snapshot_date,p_source_file_name,p_source_file_hash,jsonb_array_length(p_rows),v_user)
  returning id into v_snapshot_id;

  insert into public.inventory_snapshot_rows(
    snapshot_id,part_no,material_name,rating,warehouse,storage_bin,quantity,safety_stock,received_date,last_used_date
  )
  select v_snapshot_id,x.part_no,x.material_name,coalesce(x.rating,''),coalesce(x.warehouse,''),coalesce(x.storage_bin,''),
         coalesce(x.quantity,0),coalesce(x.safety_stock,0),x.received_date,x.last_used_date
  from jsonb_to_recordset(p_rows) as x(
    part_no text, material_name text, rating text, warehouse text, storage_bin text,
    quantity numeric, safety_stock numeric, received_date date, last_used_date date
  )
  where nullif(trim(x.part_no),'') is not null and nullif(trim(coalesce(x.warehouse,'')),'') is not null;

  select count(*) into v_row_count from public.inventory_snapshot_rows where snapshot_id=v_snapshot_id;
  if v_row_count = 0 then raise exception 'NO_VALID_ROWS'; end if;
  update public.inventory_snapshots set row_count=v_row_count where id=v_snapshot_id;

  insert into public.materials(part_no,material_name,unit)
  select distinct part_no,max(material_name),'' from public.inventory_snapshot_rows
  where snapshot_id=v_snapshot_id group by part_no
  on conflict(part_no) do update set material_name=excluded.material_name;

  if v_previous_id is not null then
    insert into public.inventory_changes(
      from_snapshot_id,to_snapshot_id,part_no,material_name,rating,warehouse,
      previous_quantity,current_quantity,quantity_delta,change_type,safety_stock
    )
    with prev as (
      select part_no,rating,warehouse,sum(quantity) quantity
      from public.inventory_snapshot_rows where snapshot_id=v_previous_id
      group by part_no,rating,warehouse
    ), curr as (
      select part_no,max(material_name) material_name,rating,warehouse,sum(quantity) quantity,max(safety_stock) safety_stock
      from public.inventory_snapshot_rows where snapshot_id=v_snapshot_id
      group by part_no,rating,warehouse
    ), merged as (
      select coalesce(c.part_no,p.part_no) part_no,coalesce(c.material_name,'') material_name,
             coalesce(c.rating,p.rating,'') rating,coalesce(c.warehouse,p.warehouse,'') warehouse,
             coalesce(p.quantity,0) previous_quantity,coalesce(c.quantity,0) current_quantity,
             coalesce(c.safety_stock,0) safety_stock
      from prev p full outer join curr c
      on p.part_no=c.part_no and p.rating=c.rating and p.warehouse=c.warehouse
    )
    select v_previous_id,v_snapshot_id,part_no,material_name,rating,warehouse,
           previous_quantity,current_quantity,current_quantity-previous_quantity,
           case when previous_quantity=0 and current_quantity<>0 then 'new'
                when previous_quantity<>0 and current_quantity=0 then 'disappeared'
                when current_quantity>previous_quantity then 'increase'
                when current_quantity<previous_quantity then 'decrease' end,
           safety_stock
    from merged where current_quantity<>previous_quantity;
    select count(*) into v_changes from public.inventory_changes where to_snapshot_id=v_snapshot_id;
  end if;

  insert into public.import_audit(snapshot_id,action,source_file_name,source_file_hash,row_count,success,operator_id)
  values(v_snapshot_id,'IMPORT',p_source_file_name,p_source_file_hash,v_row_count,true,v_user);

  return jsonb_build_object('snapshot_id',v_snapshot_id,'row_count',v_row_count,'change_count',v_changes,'previous_snapshot_id',v_previous_id);
exception when others then
  insert into public.import_audit(action,source_file_name,source_file_hash,success,error_message,operator_id)
  values('IMPORT',p_source_file_name,p_source_file_hash,false,sqlerrm,v_user);
  raise;
end;
$$;

revoke all on function public.import_inventory_snapshot(date,text,text,jsonb) from public,anon;
grant execute on function public.import_inventory_snapshot(date,text,text,jsonb) to authenticated;

create or replace function public.agent_heartbeat(
  p_machine_name text,
  p_status text default 'WAITING',
  p_last_file text default null,
  p_last_imported_date date default null,
  p_last_imported_hash text default null,
  p_last_scan timestamptz default now(),
  p_last_error text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare v_user uuid := (select auth.uid());
begin
  if v_user is null then raise exception 'AUTH_REQUIRED'; end if;
  if not (select public.is_operator_or_admin()) then raise exception 'ROLE_NOT_ALLOWED'; end if;
  insert into public.agent_status(machine_name,status,last_file,last_imported_date,last_imported_hash,last_scan_at,last_error,updated_by)
  values(p_machine_name,coalesce(p_status,'WAITING'),p_last_file,p_last_imported_date,p_last_imported_hash,coalesce(p_last_scan,now()),p_last_error,v_user)
  on conflict(machine_name) do update set status=excluded.status,last_file=excluded.last_file,
    last_imported_date=coalesce(excluded.last_imported_date,public.agent_status.last_imported_date),
    last_imported_hash=coalesce(excluded.last_imported_hash,public.agent_status.last_imported_hash),
    last_scan_at=excluded.last_scan_at,last_error=excluded.last_error,updated_by=excluded.updated_by;
  return jsonb_build_object('ok',true,'machine_name',p_machine_name);
end;
$$;

revoke all on function public.agent_heartbeat(text,text,text,date,text,timestamptz,text) from public,anon;
grant execute on function public.agent_heartbeat(text,text,text,date,text,timestamptz,text) to authenticated;

create or replace function public.get_agent_status(p_machine_name text)
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
  select coalesce(row_to_json(a)::jsonb,'{}'::jsonb)
  from public.agent_status a
  where a.machine_name=p_machine_name;
$$;

revoke all on function public.get_agent_status(text) from public,anon;
grant execute on function public.get_agent_status(text) to authenticated;

create or replace function public.get_dashboard()
returns jsonb
language sql
stable
security definer
set search_path=''
as $$
with latest as (select * from public.inventory_snapshots order by snapshot_date desc limit 1),
counts as (
 select count(*) filter(where change_type='increase') increase_count,
        count(*) filter(where change_type='decrease') decrease_count,
        count(*) filter(where change_type='new') new_count,
        count(*) filter(where change_type='disappeared') disappeared_count
 from public.inventory_changes c join latest l on l.id=c.to_snapshot_id
)
select jsonb_build_object('latest',(select row_to_json(latest) from latest),'counts',(select row_to_json(counts) from counts));
$$;

revoke all on function public.get_dashboard() from public,anon;
grant execute on function public.get_dashboard() to authenticated;
